### ISSUE TITLE
补充几个国外的组

### ISSUE THREAD

**Issue by xuhangc** [Kobaayyy/Awesome-Low-Level-Vision-Research-Groups#2]
http://yaksoy.github.io/

https://www.cs.princeton.edu/~fheide/

http://www.singbingkang.com/

http://web.stanford.edu/~gordonwz/

https://people.eecs.berkeley.edu/~efros/

https://www.cs.columbia.edu/~nayar/

https://people.epfl.ch/sabine.susstrunk

**Comment by Kobaayyy** [comment]
> http://yaksoy.github.io/
> 
> https://www.cs.princeton.edu/~fheide/
> 
> http://www.singbingkang.com/
> 
> http://web.stanford.edu/~gordonwz/
> 
> https://people.eecs.berkeley.edu/~efros/
> 
> https://www.cs.columbia.edu/~nayar/
> 
> https://people.epfl.ch/sabine.susstrunk

好的感谢，迟点更新上去
