### ISSUE TITLE
CV地区性分组

### ISSUE THREAD

**Issue by xixi-nobody** [Kobaayyy/Awesome-Low-Level-Vision-Research-Groups#4]
很不错的总结，请问后续会整理一下各个地区做CV（不仅限于low level）的团队嘛，比如香港，新加坡，澳洲。感谢！

**Comment by Kobaayyy** [comment]
> 很不错的总结，请问后续会整理一下各个地区做CV（不仅限于low level）的团队嘛，比如香港，新加坡，澳洲。感谢！

感谢支持。我主要是做底层视觉和AIGC相关，CV其他领域我没那么熟悉，所以不敢班门弄斧，等后续我对CV整个领域有个详细的了解后可能会做一些整理。PS：其实知乎上有一些帖子是有对国内大学里一些比较著名的团队进行整理，可以搜搜看。
